### ISSUE TITLE
Git generated `Merge` commit message are not accepted

### ISSUE THREAD

**Issue by mboughaba** [willsoto/validate-commit#108]
Hi,

Thanks for putting it all together, this is a nice utility.
I just noticed that git generated `Merge` messages are not accepted. Is this intended, is there a configuration to disable that?

Maybe we could add this as a global `ignorePattern`:
https://github.com/willsoto/validate-commit/blob/e4878b3d48ceac82ebe96077fc8c8979e9f567de/src/presets/angular.ts#L63

Cheers,
Mo

**Comment by willsoto** [comment]
I'm not sure how all the conventions treat merge commits, but you can pass `--no-verify` if you would like to keep it. If you'd like it to match the convention, you should be able to reword it.

**Comment by mboughaba** [comment]
found a better option https://github.com/marionebl/commitlint which might work better.
