### ISSUE TITLE
Complains about old commit

### ISSUE THREAD

**Issue by micky2be** [willsoto/validate-commit#48]
I just started to use this module on an existing project.
We just started to use Angular convention so previous commit was not following those rules.
Can we set validate-commit to avoid looking into commit history?

**Comment by willsoto** [comment]
This package does not look into old commits at all. Can you tell me more about the behavior you are seeing that makes you think that?

Are there any errors?

**Comment by micky2be** [comment]
I think it's because I was using it with pre-commit.
Working good with husky.

Can close the issue.

**Comment by willsoto** [comment]
Good to know. Thanks!
