### ISSUE TITLE
Add support for conventional commit types

### ISSUE THREAD

**Issue by jiaweihli** [willsoto/validate-commit#54]
[Conventional commits](https://github.com/commitizen/conventional-commit-types/blob/master/index.json) are used by default in a lot of other tooling.

Any chance you can add support for this?

**Comment by willsoto** [comment]
That is the default here except that I called them "Angular." See [here](https://github.com/willsoto/validate-commit/blob/master/conventions/angular.md)

**Comment by jiaweihli** [comment]
Sorry, to clarify - conventional commits are a superset of the Angular types.  There are 3 new types added: `build`, `ci`, and `revert`.

**Comment by willsoto** [comment]
Ah okay. I am happy to accept a PR to add those. [Here is where you would do it](https://github.com/willsoto/validate-commit/blob/master/src/presets/angular.ts#L22-L32).
